Repository Samsung/escargot, pull requests merged in 2019-09, with the labels that each got.

#399 Simplify isRegExpObject check
  src/api/EscargotPublic.cpp
  src/runtime/GlobalObjectBuiltinRegExp.cpp
  src/runtime/GlobalObjectBuiltinString.cpp
  src/runtime/Object.h
  src/runtime/PointerValue.h
  src/runtime/RegExpObject.cpp
  src/runtime/RegExpObject.h
  src/runtime/VMInstance.cpp
Labels: enhancement

#277 Implement the @@unscopables well-known Symbol
  src/runtime/EnvironmentRecord.h
  src/runtime/GlobalObjectBuiltinArray.cpp
Labels: ES2015

#420 Fix Object.getOwnPropertySymbols
  src/runtime/GlobalObjectBuiltinObject.cpp
Labels: bug
