Repository Samsung/escargot, pull requests merged in 2019-07, with the labels that each got.

#285 Implement the lexical scoping
  src/api/EscargotPublic.cpp
  src/interpreter/ByteCode.h
  src/interpreter/ByteCodeGenerator.cpp
  src/interpreter/ByteCodeGenerator.h
  src/interpreter/ByteCodeInterpreter.cpp
  src/interpreter/ByteCodeInterpreter.h
  src/parser/CodeBlock.cpp
  src/parser/CodeBlock.h
  src/parser/Script.cpp
  src/parser/ScriptParser.cpp
  src/parser/ScriptParser.h
  src/parser/ast/ArrayPatternNode.h
  src/parser/ast/BlockStatementNode.h
  src/parser/ast/BreakStatementNode.h
  src/parser/ast/ClassDeclarationNode.h
  src/parser/ast/ForInOfStatementNode.h
  src/parser/ast/ForStatementNode.h
  src/parser/ast/IdentifierNode.h
  src/parser/ast/Node.h
  src/parser/ast/ObjectPatternNode.h
  src/parser/ast/ProgramNode.h
  src/parser/ast/SwitchStatementNode.h
  src/parser/ast/VariableDeclarationNode.h
  src/parser/ast/VariableDeclaratorNode.h
  src/parser/esprima_cpp/esprima.cpp
  src/runtime/EnvironmentRecord.cpp
  src/runtime/EnvironmentRecord.h
  src/runtime/ErrorObject.cpp
  src/runtime/ErrorObject.h
  test/es2015/assert.js
  test/es2015/const.js
  test/es2015/let.js
Labels: ES2015

#310 Improve String.prototype.repeat
  src/runtime/GlobalObjectBuiltinString.cpp
  tools/test/v8/v8.mjsunit.status
Labels: ES2015, enhancement

#313 Update lexcial environment.
  src/Escargot.h
  src/api/EscargotPublic.cpp
  src/heap/CustomAllocator.cpp
  src/interpreter/ByteCode.cpp
  src/interpreter/ByteCode.h
  src/interpreter/ByteCodeGenerator.cpp
  src/interpreter/ByteCodeGenerator.h
  src/interpreter/ByteCodeInterpreter.cpp
  src/interpreter/ByteCodeInterpreter.h
  src/parser/CodeBlock.cpp
  src/parser/CodeBlock.h
  src/parser/Lexer.cpp
  src/parser/Script.cpp
  src/parser/ScriptParser.cpp
  src/parser/ScriptParser.h
  src/parser/ast/ArrayPatternNode.h
  src/parser/ast/ArrowFunctionExpressionNode.h
  src/parser/ast/AssignmentExpressionSimpleNode.h
  src/parser/ast/BlockStatementNode.h
  src/parser/ast/BreakStatementNode.h
  src/parser/ast/ForInOfStatementNode.h
  src/parser/ast/ForStatementNode.h
  src/parser/ast/FunctionDeclarationNode.h
  src/parser/ast/FunctionExpressionNode.h
  src/parser/ast/FunctionNode.h
  src/parser/ast/IdentifierNode.h
  src/parser/ast/LiteralNode.h
  src/parser/ast/Node.cpp
  src/parser/ast/Node.h
  src/parser/ast/ObjectPatternNode.h
  src/parser/ast/PatternNode.h
  src/parser/ast/ProgramNode.h
  src/parser/ast/SwitchStatementNode.h
  src/parser/ast/UnaryExpressionDeleteNode.h
  src/parser/ast/UnaryExpressionTypeOfNode.h
  src/parser/ast/UpdateExpressionDecrementPostfixNode.h
  src/parser/ast/UpdateExpressionDecrementPrefixNode.h
  src/parser/ast/UpdateExpressionIncrementPostfixNode.h
  src/parser/ast/UpdateExpressionIncrementPrefixNode.h
  src/parser/ast/VariableDeclarationNode.h
  src/parser/ast/VariableDeclaratorNode.h
  src/parser/esprima_cpp/esprima.cpp
  src/parser/esprima_cpp/esprima.h
  src/runtime/ArgumentsObject.cpp
  src/runtime/AtomicString.h
  src/runtime/EnvironmentRecord.cpp
  src/runtime/EnvironmentRecord.h
  src/runtime/ErrorObject.cpp
  src/runtime/ErrorObject.h
  src/runtime/ExecutionState.cpp
  src/runtime/FunctionObject.cpp
  src/runtime/SmallValue.h
  tools/test/spidermonkey/spidermonkey.excludelist.txt
Labels: ES2015, enhancement

#324 Optimize/simplify static string initialization
  src/parser/Lexer.cpp
  src/runtime/AtomicString.cpp
  src/runtime/AtomicString.h
  src/runtime/StaticStrings.cpp
  src/runtime/StaticStrings.h
Labels: enhancement
